Sounds = {}

Sounds.playerHurt = file.loadSound("assets/playerhurt.wav")
Sounds.playerDeath = file.loadSound("assets/death.wav")
Sounds.monsterHurt = file.loadSound("assets/monsterhurt.wav")
Sounds.test = file.loadSound("assets/test.wav")
Sounds.pickup = file.loadSound("assets/pickup.wav")
Sounds.bossdeath = file.loadSound("assets/bossdeath.wav")
Sounds.craft = file.loadSound("assets/craft.wav")

return Sounds
